### ISSUE TITLE
missing results.sh and question about nn updating function

### ISSUE THREAD

**Issue by YoushaaMurhij** [cogsys-tuebingen/CBMOT#3]
Thanks for sharing your work!
I can't find your launch script "results.sh"! 
Is it possible to use the nn learning_score_update_function with a tracker without fusion (only with lidar data)? can you please guide how to use it?

**Comment by J-A-Schroeder** [comment]
Thanks for your hint. Results.sh was indeed missing. It has been uploaded now.

In the Results.sh, you can set the parameter "--fusion True" to False or simply take it out (resulting in a 'false' value). In that case, only the lidar data is taken.
